"""Built-in agent profiles for experiments."""

from prdx_sim.agent import AgentProfile

DEFAULT_PROFILES: dict[str, AgentProfile] = {
    "Smart Alice": AgentProfile(
        name="Smart Alice",
        understanding=0.95,
        risk=0.15,
        patience=0.95,
        emotional=0.10,
        follow_trend=0.30,
        buy_dip=0.85,
        mine_willingness=0.0,
        mine_range=(2, 3),
        panic_at=-0.30,
        exit_at=0.5,
        target_position=0.80,
        exit_strategy="gradual",
    ),
    "Aggressive Bob": AgentProfile(
        name="Aggressive Bob",
        understanding=0.65,
        risk=0.90,
        patience=0.35,
        emotional=0.30,
        follow_trend=0.60,
        buy_dip=0.40,
        mine_willingness=0.85,
        mine_range=(6, 12),
        panic_at=-0.25,
        exit_at=0.3,
        target_position=0.50,
        exit_strategy="partial",
    ),
    "Mad Max": AgentProfile(
        name="Mad Max",
        understanding=0.65,
        risk=0.90,
        patience=0.5,
        emotional=0.30,
        follow_trend=0.60,
        buy_dip=0.40,
        mine_willingness=0.85,
        mine_range=(6, 20),
        panic_at=-0.50,
        exit_at=1.0,
        target_position=0.20,
        exit_strategy="full",
    ),
    "Panicky Charlie": AgentProfile(
        name="Panicky Charlie",
        understanding=0.20,
        risk=0.50,
        patience=0.25,
        emotional=0.80,
        follow_trend=0.85,
        buy_dip=0.10,
        mine_willingness=0.40,
        mine_range=(4, 8),
        panic_at=-0.10,
        exit_at=0.15,
        target_position=0.40,
        exit_strategy="full",
    ),
    "Balanced David": AgentProfile(
        name="Balanced David",
        understanding=0.75,
        risk=0.50,
        patience=0.70,
        emotional=0.25,
        follow_trend=0.50,
        buy_dip=0.65,
        mine_willingness=0.30,
        mine_range=(4, 8),
        panic_at=-0.20,
        exit_at=0.25,
        target_position=0.65,
        exit_strategy="gradual",
    ),
    "Conservative Emma": AgentProfile(
        name="Conservative Emma",
        understanding=0.85,
        risk=0.10,
        patience=0.90,
        emotional=0.15,
        follow_trend=0.20,
        buy_dip=0.70,
        mine_willingness=0.05,
        mine_range=(2, 8),
        panic_at=-0.25,
        exit_at=0.2,
        target_position=0.90,
        exit_strategy="partial",
    ),
    "Opportunistic Frank": AgentProfile(
        name="Opportunistic Frank",
        understanding=0.50,
        risk=0.80,
        patience=0.40,
        emotional=0.40,
        follow_trend=0.75,
        buy_dip=0.30,
        mine_willingness=0.70,
        mine_range=(5, 10),
        panic_at=-0.20,
        exit_at=0.35,
        target_position=0.60,
        exit_strategy="partial",
    ),
    "Mathematical Genius George": AgentProfile(
        name="Mathematical Genius George",
        understanding=0.98,
        risk=0.30,
        patience=0.85,
        emotional=0.05,
        follow_trend=0.10,
        buy_dip=0.90,
        mine_willingness=0.20,
        mine_range=(3, 12),
        panic_at=-0.35,
        exit_at=0.4,
        target_position=0.75,
        exit_strategy="gradual",
    ),
    "Gambler Helen": AgentProfile(
        name="Gambler Helen",
        understanding=0.40,
        risk=0.95,
        patience=0.20,
        emotional=0.70,
        follow_trend=0.80,
        buy_dip=0.20,
        mine_willingness=0.95,
        mine_range=(8, 16),
        panic_at=-0.15,
        exit_at=0.25,
        target_position=0.30,
        exit_strategy="full",
    ),
}
